### PR TITLE
#33 #49 AT's completed for Login and Register

### PR DESCRIPTION
**Pull request by dylanfernandes**
Created AT's for login and register using AT's from mern-starter as a reference. Also update the travis.yml to build for node.Js 7.

### CODE REVIEW

**Comment by jacobrs** [comment]
@dylanfernandes I get the following error after running `npm test`:
```
✖ No tests found in client/modules/User/__test__/apiLogin.spec.js, make sure to import "ava" at the top of your test file
```

**Comment by Philippe229** [comment]
@dylanfernandes Can you provide us with the steps to verify your implementation either on the PR here or in the corresponding issue?

**Comment by dylanfernandes** [comment]
@Philippe229 @jacobrs try `npm run watch:test`. Also what version of node do you guys have because I put version 7 of node in the travis?

**Comment by jacobrs** [comment]
@dylanfernandes I ran that command and I still get the error.

**Comment by dylanfernandes** [comment]
@jacobrs can you send me a screenshot of the error

**Comment by jacobrs** [comment]
@dylanfernandes 
screen shot 2017-02-04 at 3 57 07 pm

**Comment by jacobrs** [comment]
I pulled from your branch `testing` (latest code) and the loginAPI test is commented out, but I see in your latest branch it isn't weird...

**Comment by dylanfernandes** [comment]
So I can merge it?

**Pull request merged**
