### PR TITLE
wip #76 begin work on ChatComponent

### PR DESCRIPTION
**Pull request by simon-bourque**
Currently blocked until the study groups become available in the users object.  For now we can merge what I have so far so we have something to show for sprint 4

### CODE REVIEW

**Comment by pbgnz** [comment]
Phil's commit should allow the FE to get the study groups objects from the user

**Comment by simon-bourque** [comment]
This is not ready to be tested yet, We need a way to actually add other people to the study groups.  I tried doing it manually in the database but I couldn't get it to work

**Comment by Philippe229** [comment]
@simon-bourque this PR needs to be merged first because I made changes that should allow the person working on the study groups to add a study group to a user

**Comment by simon-bourque** [comment]
I was planning on discussing all this in the tutorial today because I am also blocking @samantha-kerr  who needs the commits you made in this branch to implement the study group switching

**Pull request merged**
