### PR TITLE
wip #39 - Profile dashboard design in HTML

### PR DESCRIPTION
**Pull request by samantha-kerr**
Created an initial dashboard page design in HTML. 
Profile information on the left, calendar and event listings on the right, and main content in the center.
The links in the navigation bar can be general links, and those in the content are user specific.

### CODE REVIEW

**Comment by samantha-kerr** [comment]
@jacobrs Ok, I thought to start I needed to just come up with a layout to show. I'll go over bootstrap components tonight and see what I can change, but I would appreciate the help tomorrow, thanks.

**Comment by simon-bourque** [comment]
Besides the responsiveness as jacob pointed out it looks great!

**Comment by samantha-kerr** [comment]
@simon-bourque I can definitely spice up the navbar a bit, no problem!

**Comment by MartinSpasov** [comment]
@samantha-kerr Pull request has been approved, you can merge into trunk! :)

**Pull request merged**
