### PR TITLE
#111 Study group assignement

### PR DESCRIPTION
**Pull request by ONourry**
When a study group is created, the new group is now assigned to the user who created it.

### CODE REVIEW

**Comment by simon-bourque** [comment]
Front end looks good to me

**Comment by jacobrs** [comment]
@simon-bourque let me test this.

**Comment by ONourry** [comment]
The devtool is returning an undefined in the console. It doesnt bother the creation process though. I'll still remove it since it we obviously dont want it.

**Comment by ONourry** [comment]
user_creation

**Comment by ONourry** [comment]
The type error V has been there for quite a while now. It's probably on the main too. I dont get any other error when creating a user

**Comment by simon-bourque** [comment]
@jacobrs Have you tested this yet? Is it working good?

**Comment by ONourry** [comment]
user_creation2

**Comment by ONourry** [comment]
You're right there seems to be another error triggered. This one does not prevent the user creation either though. I will try to find what is triggering it but overall it doesn't seem to have any impact on any functionality.

**Comment by ONourry** [comment]
After investigating this error. The issue seems to be with these lines in the UserReducer file:
`case ADD_USER :
      return {
        data: [action.user, ...state.data],
      };`

 The state.data property returns undefined initially. If a user is created and then the website is refreshed, the error never appears again. If no refresh is done, the error will keep showing up for every user created. The user creation however, is done normally every time regardless if the error shows up in console or not. This lets me think that the state.data is not really undefined since the correct user information is sent to the server.

My changes did not touch this file at all so that seems very weird to me.
 The fact that a refresh fixes the issue also seems like an weird behavior to me. If anyone has an idea of what might be the issue I am open to any idea/suggestion. I'll keep looking into it in the meanwhile.

**Comment by ONourry** [comment]
Ok, i just looked really quickly and this behavior happens on the main branch as well. My changes have nothing to do with it.

**Comment by simon-bourque** [comment]
@ONourry Ok but I'd still wait for jacobs approval as well

**Pull request merged**
