### PR TITLE
#66 Tests for non authenticated endpoints

### PR DESCRIPTION
**Pull request by pbgnz**
### Description
Tests for the non authenticated endpoints. Philippe and I are having trouble *mocking* a user login using ava. This means that we cannot test the *authenticated endpoints*.

The tests check the status code and the contents of the response.

Also, the studyGroups and messages endpoints were made authenticated.

### How to test the pr
Switch to the **test_api_endpoints** branch. And run the `npm t` command.

### CODE REVIEW

**Comment by pbgnz** [comment]
@Philippe229 travis failed lol

**Comment by pbgnz** [comment]
Something sketchy is going on this branch :confused:

**Comment by pbgnz** [comment]
Was thinking of excluding the backend tests from the Travis building and creating a new npm script (eg npm run test_backend) to manually lunch the tests. As of now the tests successfully pass on my local machine, can someone else verify on theirs ?

**Comment by Philippe229** [comment]
I can try it on my Windows 10 machine. Which OS did you try it on?

**Comment by pbgnz** [comment]
I tried them on ubuntu version 16.0.4

**Comment by pbgnz** [comment]
The problem is the connection to the database

**Comment by pbgnz** [comment]
Anyone knows how to make a separate script to run the back-end tests separately from the front-end tests?

**Comment by pbgnz** [comment]
Travis keeps failing because we need to start the MongoDB service. (I thought travis started it by default). It can be done by configuring the travis.yml file and adding `services: mongodb`, can somone do it today? I won't be able to do it until tomorrow morning.

**Comment by pbgnz** [comment]
💪

**Comment by dylanfernandes** [comment]
Tests coverage added for server side end points. Decrease in coverage caused by including tests for server side end points.

**Pull request merged**
